### ISSUE TITLE
Update implementations of Stream.{lastWhere, firstWhere} for Dart 2

### ISSUE THREAD

**Issue by leafpetersen** [alexeieleusis/shuttlecock#42]
We are deprecating (and will soon remove) the `defaultValue` argument from `Stream.firstWhere` and `Stream.lastWhere`.  Currently, the implementation of these methods in `StreamMonad` look like:

```dart
 @override
  FutureMonad<T> firstWhere(bool test(T element),
          {Object defaultValue(), T orElse()}) =>
      new FutureMonad(
          _stream.firstWhere(test, defaultValue: defaultValue ?? orElse));
```

At a minimum this code needs to be updated to delegate to `orElse` instead of the soon to be removed `defaultValue`, but it's probably best to remove `defaultValue` from the `StreamMonad` API as well to make it consistent.

@alexeieleusis Shall I submit a PR, and if so would you prefer that I leave defaultValue in the API for now (possibly marked as deprecated), or remove it entirely in one go.

**Comment by alexeieleusis** [comment]
@leafpetersen I am already working on it, will send a PR soon and publish updated packages to pub and internally.

**Comment by leafpetersen** [comment]
Great, thanks!  Note that we haven't removed defaultValue from the Stream API yet - you won't be able to actually remove that argument until we land an SDK with it removed.

**Comment by leafpetersen** [comment]
Sorry, I wasn't clear enough: the changes in #43 aren't forward compatible because we will be removing `defaultValue` shortly.  So for the interim we need something like:

```
@override
  FutureMonad<T> firstWhere(bool test(T element),
          {Object defaultValue(), T orElse()}) =>
      new FutureMonad(
          _stream.firstWhere(test, orElse: orElse ?? (x) => defaultValue(x)));
```

and then later on remove `defaultValue` from the `StreamMonad` API.

```
@override
  FutureMonad<T> firstWhere(bool test(T element),
          {T orElse()}) =>
      new FutureMonad(
          _stream.firstWhere(test, orElse: orElse);
```

Alternatively, we could do that change atomically (just not publish yet), but that would require the internal roll to pull this new version in atomically.  So maybe best to do in two steps?

Sorry for the hassle!
